name: attendence_admin_fultter
description: "nie college attendence app admin side"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  oktoast: ^3.3.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^1.3.0
  fluttertoast: ^8.2.4  # Use latest version
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login_main_image.png

